@startuml
User -> Redmine : Browser-Request
activate Redmine
Redmine -> application_controller : 'user_setup'
activate application_controller
application_controller -> application_controller_patch: 'cas_find_current_user'
activate application_controller_patch
application_controller_patch -> application_controller: 'find_current_user'
activate application_controller
application_controller -> application_controller: 'try_to_autologin'
activate application_controller
application_controller -> application_controller: 'try_to_autologin' returns nil
deactivate application_controller
application_controller -> application_controller: extract login and password from request (Authorization header)
application_controller -> user: 'try_to_login(username, password)'
activate user
user -> user: 'try_to_login!(username, password)'
activate user
user -> user: 'find_by_login(username)'
activate user
user -> user: return <user>
deactivate user
user -> user_patch: 'check_password_with_cas?'
activate user_patch
user_patch -> auth_source_cas: 'authenticate'
activate auth_source_cas
auth_source_cas -> auth_source_cas: do cas proxy ticket workflow
auth_source_cas -> user_manager: 'create_or_update_user'
activate user_manager
user_manager -> user_manager: create/update user
user_manager -> auth_source_cas: return <user>
deactivate user_manager
auth_source_cas -> user_patch: return <user>
deactivate auth_source_cas
user_patch -> user: return true
deactivate user_patch
user -> user: return <user>
deactivate user
user -> application_controller: return <user>
deactivate user
application_controller -> application_controller_patch: return <user>
deactivate application_controller
application_controller_patch -> application_controller: return <user>
deactivate application_controller_patch
application_controller -> Redmine: User.curent=<user>
deactivate application_controller
Redmine -> User: Show requested page
deactivate Redmine
@enduml

/'
EcoSystem plantuml link:
https://ecosystem.cloudogu.com/plantuml/uml/lPNDJiCm3CVlVGfp0YG6zuaFmIE0Tev2wgtHkgGu2MKyFKwsqQvREueGjtpO_rzYEyxC8S7a7funNsc3C8KdiZKlJfxnBQ3pcLHUlqkFEvDiPyfUigfAhQJNrWXbZITRbgmtXVF04iAX3zLvet3SFEjHwTKNbVIgO8YIJioroOKAH6YyYDIJl8rxDhJPpsRgUEBe6pB5qrfuAsJmjhGBRVu70iGf8-F0w3BByU-H-E69LI7XG9eSAkbSRIc7ETaLyrFLmSLZy8Kb_Paae42P8rqE06CYcXib-OkuPkGAhxuXbwqmnjqik5xtir_ufzfuNNVu9xmsCOVREBjlH_t0jgdy0jLIx4ubQkqBmQ_XeGFQbdepJAdXo0fd0ocCFgmMLxYOOs2nNMVxXbbdVbGhjn2tAh8VQs359NhW8oxdfQsF2QIZhQIHYnG_HSXaOKc4Ae-ZpljgcsVjoQ7MHkfcezE4ikrmSFh1J7np-wwnJKwlI3UU-sdPgmLF0G_uJJB7raxVQnps_crVxW_0c2vokXEFv0ps_TOVE8KP2rvpX-StSVVZMxI-nLbApKjXwrq_mzZd5diftTf_0G00
'/