@startuml
User -> Redmine : Browser-Request
activate Redmine
Redmine -> application_controller_patch : 'cas_user_setup'
activate application_controller_patch
application_controller_patch -> application_controller : 'user_setup'
activate application_controller
application_controller -> application_controller_patch: 'cas_find_current_user'
activate application_controller_patch
application_controller_patch -> application_controller: 'find_current_user'
activate application_controller
application_controller -> application_controller: 'try_to_autologin'
activate application_controller
application_controller -> application_controller: 'try_to_autologin' returns nil
deactivate application_controller
application_controller -> application_controller: extract login and password from request (Authorization header)
application_controller -> user: 'try_to_login(username, password)'
activate user
user -> user: 'try_to_login!(username, password)'
activate user
user -> user: 'find_by_login(username)'
activate user
user -> user: return <user>
deactivate user
user -> user_patch: 'check_password_with_cas?'
activate user_patch
user_patch -> auth_source_cas: 'authenticate'
activate auth_source_cas
auth_source_cas -> auth_source_cas: do cas proxy ticket workflow
auth_source_cas -> user_manager: 'create_or_update_user'
activate user_manager
user_manager -> user_manager: create/update user
user_manager -> auth_source_cas: return <user>
deactivate user_manager
auth_source_cas -> user_patch: return <user>
deactivate auth_source_cas
user_patch -> user: return true
deactivate user_patch
user -> user: return <user>
deactivate user
user -> application_controller: return <user>
deactivate user
application_controller -> application_controller_patch: return <user>
deactivate application_controller
application_controller_patch -> application_controller: return <user>
deactivate application_controller_patch
application_controller -> application_controller: User.curent=<user>
application_controller -> application_controller_patch
deactivate application_controller
application_controller_patch -> application_controller_patch: reload: User.current = User.find_by_login(User.current.login)
application_controller_patch -> Redmine
deactivate application_controller_patch
Redmine -> User: Show requested page
deactivate Redmine
@enduml

/'
EcoSystem plantuml link:
https://ecosystem.cloudogu.com/plantuml/uml/lLR9RkCm3BtxApIdDC0qlG-wOEOJMkGiQ2Gc5k98BYNLJR--b6BNIsgd3gPpqqA-HpvIXDOEa5tViqTGUss0_M9_q5PqUFq8pm6SpuJq-aLuQ4oonfIyH5aMMWglhU7I6e-sA01vARpC2MeXXUE1mBW37yf5YpNbc4sYZh96lXbS8opdiggJscYZk0o8O7pAy7jp8zRvZBCp91QF1-uj5y7Rmcwr-Jya3AbaQ1mpkiWK_7jAUFL8g2pHCM4KAuLpbKN5DcZtn9zwdLtz3ZwtgDyI1Cj1AC3b164iH9jHWh-APqRiuUS7oR8ZOxpDWXjr_t61V-gDluS1_ncle-RiDkxkkwgVsBQTduFSyIOgNccVSteD3mEYkjNRPIeDASkT3IWX-X1QFA5cZi92jy_wXjbW_ocMiYnUbMXV3umGT-0PXRZR5BRw3225jXT6R9D-4e6OkKKUIXLNW_VLDS-wcrEi8zJD4QULikjm4lra9JvunzAeYpCACjIpNvPUBtWCSCBV5dDkxuozncdlI-Vok01pfiZvIJoJPtBkJ_6i2Nz50v-Uo5rDTfaqtwP5gtnXXMeZZY6pk-EsFvgw5gjqj3pBtNmxlgfqvtkoJitwbDkgcV0G9_-s1rRRlmC0
'/