@startuml
User -> Redmine : Browser-Request
activate Redmine
Redmine -> application_controller_patch : 'cas_user_setup'
activate application_controller_patch
application_controller_patch -> application_controller : 'user_setup'
activate application_controller
application_controller -> application_controller_patch: 'cas_find_current_user'
activate application_controller_patch
activate application_controller
application_controller_patch -> application_controller: 'find_current_user'
activate application_controller
application_controller -> application_controller: 'try_to_autologin'
application_controller -> application_controller: 'try_to_autologin' returns nil
deactivate application_controller
application_controller -> application_controller_patch: 'find_current_user' returns nil
deactivate application_controller
application_controller_patch -> application_controller: 'cas_find_current_user' returns nil
deactivate application_controller_patch
application_controller -> application_controller: User.current = nil
application_controller -> application_controller_patch
application_controller_patch -> Redmine
deactivate application_controller_patch
deactivate application_controller
Redmine -> Redmine: before_action hook (check_if_login_required)
Redmine -> application_controller_patch : 'cas_check_if_login_required'
activate application_controller_patch
application_controller_patch -> application_controller : 'check_if_login_required'
activate application_controller
application_controller -> application_controller_patch: 'require_login_with_cas'
deactivate application_controller
application_controller_patch -> Redmine: Redirect to action (account_controller_patch::cas)
deactivate application_controller_patch
Redmine -> application_controller_patch : 'cas_user_setup'
activate application_controller_patch
application_controller_patch -> application_controller : 'user_setup'
activate application_controller
application_controller -> application_controller_patch: 'cas_find_current_user'
activate application_controller_patch
activate application_controller
application_controller_patch -> application_controller: 'find_current_user'
activate application_controller
application_controller -> application_controller: 'try_to_autologin'
application_controller -> application_controller: 'try_to_autologin' returns nil
deactivate application_controller
application_controller -> application_controller_patch: 'find_current_user' returns nil
deactivate application_controller
application_controller_patch -> application_controller: 'cas_find_current_user' returns nil
deactivate application_controller_patch
application_controller -> application_controller: User.current = nil
application_controller -> application_controller_patch
application_controller_patch -> Redmine
deactivate application_controller_patch
deactivate application_controller
Redmine -> application_controller_patch: 'cas'
activate application_controller_patch
application_controller_patch -> Redmine
deactivate application_controller_patch
Redmine -> Redmine: 'CASClient::Frameworks::Rails::Filter' handles redirect
note over Redmine: The filter is registered at app startup in 'redmine_cas::setup!'
Redmine -> User: Redirect to cas login url
deactivate Redmine
User -> User: Do cas Workflow (enter credentials, ...)
User -> Redmine: Browser request containing cas-ST
activate Redmine
Redmine -> Redmine: Validate ST and add user attributes to session
Redmine -> account_controller_patch: 'cas'
activate account_controller_patch
account_controller_patch -> user_manager: 'create_or_update_user'
activate user_manager
user_manager -> user_manager: create/update user
user_manager -> account_controller_patch: 'create_or_update_user' returns the created/updated user
deactivate user_manager
account_controller_patch -> application_controller: 'logged_user='
activate application_controller
application_controller -> application_controller: destroy session
application_controller -> Redmine: User.current=user
application_controller -> account_controller_patch: return
deactivate application_controller
account_controller_patch -> account_controller_patch: 'redirect_to_ref_or_default'
account_controller_patch -> Redmine: return
deactivate account_controller_patch
Redmine -> User: Render page with correct user
deactivate Redmine
@enduml

/'
EcoSystem plantuml link:
https://ecosystem.cloudogu.com/plantuml/uml/xLTDRzim3BtxLt0dfy2ItGramDQXFo0Vsr5G9JaMeaYU93VelnybErxIn4uS93tbLBSc-SX7yh5UEc5X_1rcWc-a5f31Jsks-CVnJFojXFC9PLw-KIzs9idE5BreMIh9g9T64sQqjqOfOKb9FIimLCge8nK68qxugap_n-fpJ7gZTg86l05O7IZdgcgAogNcX5NM2krZXHVNTbLMvsh7h8PdD9W1HF7sdNX3QEMDCYkfqvi40Oijizg1bYhXucwTE-Re9iWNTEVqp0n3xzsEFlGbOaqQO9X6iEieXBC4x3JYqcBEKxwdDirZ1gyYDrQGu6eq5CQiOSGAmTP4vYIE5B6eNj8A_ZHKhZhYt5-xhWM-VXqQY0PmAtr1a87q1dlGTWeV485vy0QQTeqeOwR25JZAA4Fqfuj7vt667cVeSOOUP-ZJpz3vlRoLmWmjuzIjJ9z_p9-LHCwpxCNIZTWQktPPDgDIuOyNgNmOWO9gheJ3KQW5Ez46qSmRTgCDjIW4vD4UPB1SIOVFWWFr8IzmdbhKF90wt9Re50vAbaKf_9BkvnU6uV0ye2N4FOJA7epXZeLbywbIk_wgFVvWDRaoMnXXXVYU8J0-IQhSLvXC9a-jMrj6yu43jlx0WK0ZbLhgLOWudYzwFtdQCB-faZmOpHU0v07b7C8w8HlUojVA8vjObXFEORCE1gZh01uDJuTXqlKYH8_7PqCrNTKhRmM68iQIgWpfVXJbVVDa_vVZM7MeRtMS-Ex8eQ-qaucqskDnk6eJtY3KTEvFma6kVHnq2Y0Es4hm23sznsNYE53MlBTTxuxGpj6-B4vZnJsmdVJMD5voE_few-xUJXV2nRGY3sta8gULycbloBRC4mbsJVS9cT0S2IYnxn3-JSMLjL4sFWv8u_aF
'/